colors:
  # Default colors
  primary:
    background: '0x080808'
    foreground: '0xeaeaea'

  # Normal colors
  normal:
    black:   '0x242424'
    red:     '0xb21b3c'
    green:   '0x26890c'
    yellow:  '0xffa602'
    blue:    '0x1368ce'
    magenta: '0x46178f'
    cyan:    '0x0aa3a3'
    white:   '0xffffff'

  # Bright colors
  bright:
    black:   '0x565656'
    red:     '0xff3355'
    green:   '0x66bf39'
    yellow:  '0xffc00a'
    blue:    '0x45a3e5'
    magenta: '0x864cbf'
    cyan:    '0x33cccc'
    white:   '0xffffff'
